name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: Release
  VERSION_MAJOR: 0
  VERSION_MINOR: 0
  VERSION_PATCH: ${{github.run_number}}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DOTUSCPP_BUILD_VERSION="${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}" --target install

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-release --config ${{env.BUILD_TYPE}}

      - name: Install Tree
        run: sudo apt install tree

      - name: Print Tree
        run: tree ${{github.workspace}}/cmake-build-release

      - name: Run tests
        run: ctest --test-dir ${{github.workspace}}/cmake-build-release

  build-macosx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DOTUSCPP_BUILD_VERSION="${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}" --target install

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-release --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: ctest --test-dir ${{github.workspace}}/cmake-build-release

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DOTUSCPP_BUILD_VERSION="${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}" --target install

      - name: Build
        run: cmake --build ${{github.workspace}}/cmake-build-release --config ${{env.BUILD_TYPE}}

      - name: Run tests
        run: ctest --test-dir ${{github.workspace}}/cmake-build-release
