name: Release

on:
  push:
    branches:
      - releases/**

env:
  BUILD_TYPE: Release
  VERSION_MAJOR: 0
  VERSION_MINOR: 1
  VERSION_PATCH: ${{github.run_number}}

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Conan
      run: pip3 install conan

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DOTUSCPP_BUILD_VERSION="${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-release --config ${{env.BUILD_TYPE}}

    - name: Pack
      run: cpack --config ${{github.workspace}}/cmake-build-release/CPackConfig.cmake

    - name: Upload Artifact DEB
      uses: actions/upload-artifact@v2
      with:
        name: otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-Linux.deb
        path: ./otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-Linux.deb

    - name: Upload Artifact TAR.GZ
      uses: actions/upload-artifact@v2
      with:
        name: otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-Linux.tar.gz
        path: ./otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-Linux.tar.gz

  build-macosx:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: pip3 install conan

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DOTUSCPP_BUILD_VERSION="${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-release --config ${{env.BUILD_TYPE}}

    - name: Pack
      run: cpack --config ${{github.workspace}}/cmake-build-release/CPackConfig.cmake

    - name: Upload Artifact ZIP
      uses: actions/upload-artifact@v2
      with:
        name: otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-Darwin.zip
        path: ./otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-Darwin.zip

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install conan
      run: pip3 install conan

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/cmake-build-release -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TESTS=ON -DOTUSCPP_BUILD_VERSION="${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-release --config ${{env.BUILD_TYPE}}

    - name: Pack
      run: cpack --config ${{github.workspace}}/cmake-build-release/CPackConfig.cmake

    - name: Upload Artifact ZIP
      uses: actions/upload-artifact@v2
      with:
        name: otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-win64.zip
        path: ./otuscpp-${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}-win64.zip

  create-release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-macosx, build-windows]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: v${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}
        release_name: Release ${{env.VERSION_MAJOR}}.${{env.VERSION_MINOR}}.${{env.VERSION_PATCH}}
        draft: true
        prerelease: false

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        path: downloaded_artifacts

    - name: Upload artifacts
      id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: downloaded_artifacts

